# Generated by Django 4.1.5 on 2023-01-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrCode', '0005_qrcode_painel_nome_qrcode_projeto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='observacoes',
            field=models.TextField(default=''),
        ),
    ]
